### ISSUE TITLE
数组越界了是什么原因啊

### ISSUE THREAD

**Issue by MusaHao** [CNU105/BUY-HW#2]

**Comment by MusaHao** [comment]
DevTools listening on ws://127.0.0.1:54197/devtools/browser/f59f5318-b975-49f1-bbff-66652d48ab1b
131********输入了账号密码，等待手动登录
131********登录成功！
131********打开购买页面
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Admin\Desktop\demo.py", line 124, in loginMall
    goToBuy(driver, user)
  File "C:\Users\Admin\Desktop\demo.py", line 83, in goToBuy
    text = driver.find_elements_by_xpath('//*[@id="pro-operation"]/a/span')[0].text
IndexError: list index out of range

**Comment by MusaHao** [comment]
登陆过程中  没有跳转登陆界面  然后需要手动填写验证码

**Comment by zhaiqi9999** [comment]
我也是一样的问题，请问如何解决，越界就无法判断button的内容了
